#### read data

In [197]:
import pandas as pd

In [198]:
df=pd.read_csv("DataSets/adult.csv")
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

#### Count total NaNs per column

In [199]:
df.isna().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

#### Summary Statistics

In [200]:
df.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [201]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [202]:
df.income.value_counts()

income
<=50K    37155
>50K     11687
Name: count, dtype: int64

#### Label Encoder for target

In [203]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['income'] = le.fit_transform(df['income'])
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,0
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,0
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,1
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,1
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,0
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,0
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,0
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,1

#### Separate Features and Target

In [204]:
X = df.drop('income', axis=1)
y = df['income']

#### Identify the column

In [205]:
categorical_cols = X.select_dtypes(include=['object']).columns
categorical_cols

Index(['workclass', 'education', 'marital-status', 'occupation',
       'relationship', 'race', 'gender', 'native-country'],
      dtype='object')

#### onehot

#### Define the ColumnTransformer

In [206]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(drop='first', sparse_output=False), categorical_cols)
    ],
    remainder='passthrough'
)

#### Transform the data

In [207]:
X_encoded = ct.fit_transform(X)

#### Convert to DataFrame

In [208]:
import pandas as pd

encoded_feature_names = ct.get_feature_names_out()
X_encoded_df = pd.DataFrame(X_encoded, columns=encoded_feature_names)

In [209]:
X_encoded_df

,onehot__workclass_Federal-gov,onehot__workclass_Local-gov,onehot__workclass_Never-worked,onehot__workclass_Private,onehot__workclass_Self-emp-inc,onehot__workclass_Self-emp-not-inc,onehot__workclass_State-gov,onehot__workclass_Without-pay,onehot__education_11th,onehot__education_12th,...,onehot__native-country_Trinadad&Tobago,onehot__native-country_United-States,onehot__native-country_Vietnam,onehot__native-country_Yugoslavia,remainder__age,remainder__fnlwgt,remainder__educational-num,remainder__capital-gain,remainder__capital-loss,remainder__hours-per-week
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,25.0,226802.0,7.0,0.0,0.0,40.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,38.0,89814.0,9.0,0.0,0.0,50.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,28.0,336951.0,12.0,0.0,0.0,40.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,44.0,160323.0,10.0,7688.0,0.0,40.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,18.0,103497.0,10.0,0.0,0.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,27.0,257302.0,12.0,0.0,0.0,38.0
48838,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,40.0,154374.0,9.0,0.0,0.0,40.0
48839,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,58.0,151910.0,9.0,0.0,0.0,40.0
48840,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,22.0,201490.0,9.0,0.0,0.0,20.0
48841,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,52.0,287927.0,9.0,15024.0,0.0,40.0

#### spilit

In [210]:
# If you haven't already:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded_df, y,
    test_size=0.2,          # 20% for testing
    random_state=42,        # reproducible
    stratify=y              # optional, good for classification
)

#### Train a Tree then a Bagging Model

In [211]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

#### for a single tree

In [212]:
# Train single decision tree
tree = DecisionTreeClassifier(random_state=42)
tree.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [213]:
# Evaluate
y_pred_tree = tree.predict(X_test)
print("Decision Tree Test Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_tree))

Decision Tree Test Accuracy: 0.8190193469137066
Confusion Matrix:
 [[6521  910]
 [ 858 1480]]

In [215]:
y_train_pred = tree.predict(X_train)
print("Tree Training Accuracy:", accuracy_score(y_train, y_train_pred))

Tree Training Accuracy: 0.9999488137588616

#### Bagging

In [216]:
bagging_model = BaggingClassifier(
    estimator=DecisionTreeClassifier(),  # base model
    n_estimators=50,                     # number of trees
    random_state=42                     # reproducibility
)

In [217]:
bagging_model.fit(X_train, y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=50,
                  random_state=42)

In [218]:
y_pred = bagging_model.predict(X_test)

In [219]:
print("✅ Bagging accuracy test:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

✅ Bagging accuracy test: 0.8568942573446617

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.93      0.91      7431
           1       0.74      0.62      0.68      2338

    accuracy                           0.86      9769
   macro avg       0.81      0.78      0.79      9769
weighted avg       0.85      0.86      0.85      9769

In [220]:
y_train_pred = bagging_model.predict(X_train)
print("Bagging Training Accuracy:", accuracy_score(y_train, y_train_pred))

Bagging Training Accuracy: 0.9994881375886162

#### I faced overfitting

In [221]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

bagging_model1 = BaggingClassifier(
    estimator=DecisionTreeClassifier(
        max_depth=3,
        min_samples_split=20,
        min_samples_leaf=10
    ),
    n_estimators=100,
    max_samples=0.7,
    max_features=0.6,
    bootstrap=True,
    bootstrap_features=True,  # <--- change here
    oob_score=True,
    random_state=42
)

In [222]:
bagging_model1.fit(X_train, y_train)

BaggingClassifier(bootstrap_features=True,
                  estimator=DecisionTreeClassifier(max_depth=3,
                                                   min_samples_leaf=10,
                                                   min_samples_split=20),
                  max_features=0.6, max_samples=0.7, n_estimators=100,
                  oob_score=True, random_state=42)

In [223]:
y_pred1 = bagging_model1.predict(X_test)

In [224]:
print("✅ Bagging accuracy test1:", accuracy_score(y_test, y_pred1))
print("\nClassification Report:\n", classification_report(y_test, y_pred1))

✅ Bagging accuracy test1: 0.8475790766711024

Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.97      0.91      7431
           1       0.83      0.46      0.59      2338

    accuracy                           0.85      9769
   macro avg       0.84      0.71      0.75      9769
weighted avg       0.85      0.85      0.83      9769

In [225]:
y_train_pred1 = bagging_model.predict(X_train)
print("Bagging Training Accuracy1:", accuracy_score(y_train, y_train_pred1))

Bagging Training Accuracy1: 0.9994881375886162

#### Dimensionality reduction with TruncatedSVD

In [226]:
from sklearn.decomposition import TruncatedSVD


svd = TruncatedSVD(n_components=20, random_state=42)
X_train_reduced = svd.fit_transform(X_train)
X_test_reduced = svd.transform(X_test)

In [227]:
bagging_model2 = BaggingClassifier(
    estimator=DecisionTreeClassifier(max_depth=3, min_samples_leaf=20),
    n_estimators=100,
    max_samples=0.7,
    max_features=0.6,
    bootstrap=True,
    bootstrap_features=True,  # random subset of features per tree
    oob_score=True,
    random_state=42
)

In [228]:
#Train
bagging_model2.fit(X_train_reduced, y_train)

BaggingClassifier(bootstrap_features=True,
                  estimator=DecisionTreeClassifier(max_depth=3,
                                                   min_samples_leaf=20),
                  max_features=0.6, max_samples=0.7, n_estimators=100,
                  oob_score=True, random_state=42)

In [229]:
#Evaluate
y_train_pred = bagging_model2.predict(X_train_reduced)
y_test_pred = bagging_model2.predict(X_test_reduced)

In [230]:

print("Train Accuracy:", accuracy_score(y_train, y_train_pred))
print("Test Accuracy:", accuracy_score(y_test, y_test_pred))
print("OOB Score:", bagging_model2.oob_score_)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))

Train Accuracy: 0.8113019220433547
Test Accuracy: 0.8102159893540792
OOB Score: 0.8141171653059658
Confusion Matrix:
 [[7419   12]
 [1842  496]]