In [26]:
import pandas as pd

In [27]:
df=pd.read_csv("grade data/student_grades_modified.csv")
df.head(5)

   Student ID              Course Grade
0         1.0                Math     F
1         1.0             Science     C
2         1.0             History     A
3         1.0             English     F
4         1.0  Physical Education     C

In [28]:
#  returns True when there is at least one missing value
df.isnull().values.any()

np.True_

In [36]:
df.isnull().sum()

Student ID    0
Course        5
Grade         0
dtype: int64

In [30]:
# Show rows with any missing values
missing_rows = df[df.isnull().any(axis=1)]
print(missing_rows)

       Student ID              Course Grade
189          38.0                 NaN     B
769         154.0                 NaN     D
1267          NaN             History     F
1685          NaN                Math     F
1899        380.0  Physical Education   NaN
2433          NaN             English     F
6265       1254.0                Math   NaN
15795         NaN                Math     B
17568      3514.0                 NaN     C
18431      3687.0             Science   NaN
18942      3789.0                 NaN     F
19118      3824.0                 NaN     D
27480         NaN                Math     C
28693         NaN             English     C
37194      7439.0  Physical Education   NaN
38158      7632.0             English   NaN
41434      8287.0  Physical Education   NaN
44131      8827.0             Science   NaN
44732         NaN             History     D
47191         NaN             Science     D

#### 1.Drop Missing Data

In [31]:
dg=df.dropna()  # Removes rows with any missing values
dg

       Student ID              Course Grade
0             1.0                Math     F
1             1.0             Science     C
2             1.0             History     A
3             1.0             English     F
4             1.0  Physical Education     C
...           ...                 ...   ...
49995     10000.0                Math     D
49996     10000.0             Science     F
49997     10000.0             History     B
49998     10000.0             English     F
49999     10000.0  Physical Education     F

[49980 rows x 3 columns]

#### 2.Fill with Statistical Measures

In [33]:
# Option 1: Fill with a Placeholder (for categorical)
df['Grade'].fillna('o', inplace=True)

In [34]:
# Option 2: Fill with Mode (most frequent value)
df['Student ID'].fillna(df['Student ID'].mode()[0], inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_4424\4016101592.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Student ID'].fillna(df['Student ID'].mode()[0], inplace=True)

In [35]:
df

       Student ID              Course Grade
0             1.0                Math     F
1             1.0             Science     C
2             1.0             History     A
3             1.0             English     F
4             1.0  Physical Education     C
...           ...                 ...   ...
49995     10000.0                Math     D
49996     10000.0             Science     F
49997     10000.0             History     B
49998     10000.0             English     F
49999     10000.0  Physical Education     F

[50000 rows x 3 columns]