# Import libraries

In [37]:
import pandas as pd
import numpy as np

# Load dataset

In [38]:
rows = 2000  # set None to load full dataset

data = pd.read_csv('/kaggle/input/datasets/rtatman/blog-authorship-corpus/blogtext.csv', nrows=rows)

r, c = data.shape
print(f'There are {r} rows and {c} columns')

There are 2000 rows and 7 columns

In [39]:
data

,id,gender,age,topic,sign,date,text
0,2059027,male,15,Student,Leo,"14,May,2004","Info has been found (+/- 100 pages,..."
1,2059027,male,15,Student,Leo,"13,May,2004",These are the team members: Drewe...
2,2059027,male,15,Student,Leo,"12,May,2004",In het kader van kernfusie op aarde...
3,2059027,male,15,Student,Leo,"12,May,2004",testing!!! testing!!!
4,3581210,male,33,InvestmentBanking,Aquarius,"11,June,2004",Thanks to Yahoo!'s Toolbar I can ...
...,...,...,...,...,...,...,...
1995,589736,male,35,Technology,Aries,"05,August,2004",Mir...*lmao*... Too funny. :) ...
1996,589736,male,35,Technology,Aries,"05,August,2004",as you read this section of the art...
1997,589736,male,35,Technology,Aries,"05,August,2004",i guess the same could have been as...
1998,589736,male,35,Technology,Aries,"05,August,2004",For the PC gamers out there: urlL...
1999,589736,male,35,Technology,Aries,"05,August,2004",WTF. urlLink Michael Jackson dang...

In [40]:
text_col = data['text']
text_col[:5]
text_col

0                  Info has been found (+/- 100 pages,...
1                  These are the team members:   Drewe...
2                  In het kader van kernfusie op aarde...
3                        testing!!!  testing!!!
4                    Thanks to Yahoo!'s Toolbar I can ...
                              ...
1995               Mir...*lmao*...  Too funny. :)     ...
1996               as you read this section of the art...
1997               i guess the same could have been as...
1998               For the PC gamers out there:   urlL...
1999               WTF.   urlLink Michael Jackson dang...
Name: text, Length: 2000, dtype: object

# Simple preprocessing

In [41]:
text_clean = text_col.str.lower()
text_clean[:5]
text_clean

0                  info has been found (+/- 100 pages,...
1                  these are the team members:   drewe...
2                  in het kader van kernfusie op aarde...
3                        testing!!!  testing!!!
4                    thanks to yahoo!'s toolbar i can ...
                              ...
1995               mir...*lmao*...  too funny. :)     ...
1996               as you read this section of the art...
1997               i guess the same could have been as...
1998               for the pc gamers out there:   urll...
1999               wtf.   urllink michael jackson dang...
Name: text, Length: 2000, dtype: object

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=500)
vecs = tfidf.fit_transform(text_clean)

vecs.shape

(2000, 500)

# Show sample vectors

In [43]:
vecs.toarray()[:3]

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.04428429, 0.0077036 , 0.04395613, ..., 0.25963863, 0.20674381,
        0.02318555]])

# Count categories in each column

In [44]:
print("Gender categories:", data['gender'].nunique())
print("Age categories:", data['age'].nunique())
print("Topic categories:", data['topic'].nunique())
print("Blogger ID categories:", data['id'].nunique())
print("Sign categories:", data['sign'].nunique())

Gender categories: 2
Age categories: 17
Topic categories: 16
Blogger ID categories: 53
Sign categories: 12

# Add TF‑IDF as one column

In [45]:
import numpy as np

data['tfidf'] = list(vecs.toarray())
data

,id,gender,age,topic,sign,date,text,tfidf
0,2059027,male,15,Student,Leo,"14,May,2004","Info has been found (+/- 100 pages,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,2059027,male,15,Student,Leo,"13,May,2004",These are the team members: Drewe...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,2059027,male,15,Student,Leo,"12,May,2004",In het kader van kernfusie op aarde...,"[0.04428429312628407, 0.007703601619145569, 0...."
3,2059027,male,15,Student,Leo,"12,May,2004",testing!!! testing!!!,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,3581210,male,33,InvestmentBanking,Aquarius,"11,June,2004",Thanks to Yahoo!'s Toolbar I can ...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...,...,...,...,...,...
1995,589736,male,35,Technology,Aries,"05,August,2004",Mir...*lmao*... Too funny. :) ...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1996,589736,male,35,Technology,Aries,"05,August,2004",as you read this section of the art...,"[0.0, 0.11856129848554853, 0.0, 0.0, 0.0, 0.0,..."
1997,589736,male,35,Technology,Aries,"05,August,2004",i guess the same could have been as...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.21158218927367828,..."
1998,589736,male,35,Technology,Aries,"05,August,2004",For the PC gamers out there: urlL...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1999,589736,male,35,Technology,Aries,"05,August,2004",WTF. urlLink Michael Jackson dang...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [46]:
data.columns

Index(['id', 'gender', 'age', 'topic', 'sign', 'date', 'text', 'tfidf'], dtype='object')

# Keep only tfidf features and gender label for classification

In [47]:
new_data = data[['tfidf', 'gender']]
new_data

                                                  tfidf gender
0     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   male
1     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   male
2     [0.04428429312628407, 0.007703601619145569, 0....   male
3     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   male
4     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   male
...                                                 ...    ...
1995  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   male
1996  [0.0, 0.11856129848554853, 0.0, 0.0, 0.0, 0.0,...   male
1997  [0.0, 0.0, 0.0, 0.0, 0.0, 0.21158218927367828,...   male
1998  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   male
1999  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   male

[2000 rows x 2 columns]

# Check gender balance

In [48]:
# check if male and female counts are balanced
print(new_data['gender'].value_counts())

gender
male      1272
female     728
Name: count, dtype: int64

#  Convert gender labels to numeric values

In [49]:
gender_map = {'male': 0, 'female': 1}
y = new_data['gender'].map(gender_map)

# Define X as the tfidf feature matrix

In [50]:
X = np.array(new_data['tfidf'].tolist())

# Define all classifiers once

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

log_reg = LogisticRegression(max_iter=1000)
svm = SVC()
rf = RandomForestClassifier()
nb = GaussianNB()

# Define all hyperparameters once

In [52]:
log_reg_params = {
    "C": [0.1, 1, 10],
    "solver": ["lbfgs"]
}

svm_params = {
    "C": [0.1, 1, 10],
    "kernel": ["linear", "rbf"]
}

rf_params = {
    "n_estimators": [100, 200],
    "max_depth": [None, 10, 20]
}

nb_params = {
    "var_smoothing": [1e-9, 1e-8, 1e-7]
}

# Train each classifier with GridSearchCV

In [53]:
from sklearn.model_selection import GridSearchCV

log_reg_grid = GridSearchCV(log_reg, log_reg_params, cv=5, scoring="accuracy")
log_reg_grid.fit(X, y)

svm_grid = GridSearchCV(svm, svm_params, cv=5, scoring="accuracy")
svm_grid.fit(X, y)

rf_grid = GridSearchCV(rf, rf_params, cv=5, scoring="accuracy")
rf_grid.fit(X, y)

nb_grid = GridSearchCV(nb, nb_params, cv=5, scoring="accuracy")
nb_grid.fit(X, y)

GridSearchCV(cv=5, estimator=GaussianNB(),
             param_grid={'var_smoothing': [1e-09, 1e-08, 1e-07]},
             scoring='accuracy')

# Collect results

In [55]:
results = {
    "log_reg": {
        "score": log_reg_grid.best_score_,
        "params": log_reg_grid.best_params_
    },
    "svm": {
        "score": svm_grid.best_score_,
        "params": svm_grid.best_params_
    },
    "rf": {
        "score": rf_grid.best_score_,
        "params": rf_grid.best_params_
    },
    "nb": {
        "score": nb_grid.best_score_,
        "params": nb_grid.best_params_
    }
}

results

{'log_reg': {'score': np.float64(0.666),
  'params': {'C': 10, 'solver': 'lbfgs'}},
 'svm': {'score': np.float64(0.6755), 'params': {'C': 1, 'kernel': 'linear'}},
 'rf': {'score': np.float64(0.6475000000000001),
  'params': {'max_depth': 20, 'n_estimators': 200}},
 'nb': {'score': np.float64(0.5820000000000001),
  'params': {'var_smoothing': 1e-08}}}

# View results cleanly (sorted by score)

In [56]:
sorted_results = sorted(
    results.items(),
    key=lambda x: x[1]["score"],
    reverse=True
)

sorted_results

[('svm',
  {'score': np.float64(0.6755), 'params': {'C': 1, 'kernel': 'linear'}}),
 ('log_reg',
  {'score': np.float64(0.666), 'params': {'C': 10, 'solver': 'lbfgs'}}),
 ('rf',
  {'score': np.float64(0.6475000000000001),
   'params': {'max_depth': 20, 'n_estimators': 200}}),
 ('nb',
  {'score': np.float64(0.5820000000000001),
   'params': {'var_smoothing': 1e-08}})]