In [60]:
import pandas as pd

# Load the dataset
df = pd.read_csv("DataSets/loan_data.csv") 
df

,Text,Income,Credit_Score,Loan_Amount,DTI_Ratio,Employment_Status,Approval
0,I need a loan to pay for an international vaca...,26556,581,8314,79.26,employed,Rejected
1,I want to make home improvements like installi...,197392,389,111604,22.14,employed,Rejected
2,"I need a loan for home renovation, including a...",44561,523,34118,45.44,employed,Rejected
3,I need funds to buy new furniture and applianc...,190363,729,118757,10.22,unemployed,Rejected
4,I need a loan to start a small business.,61853,732,19210,44.13,employed,Approved
...,...,...,...,...,...,...,...
23995,I need funds to pay for my daughter's college ...,195242,817,16403,24.32,employed,Approved
23996,I need financial assistance to launch my own Y...,150246,729,101572,9.97,employed,Rejected
23997,I need money to open a small bookstore and café.,64571,650,30533,57.35,employed,Rejected
23998,I want to buy a car for my rideshare business ...,115825,418,89837,10.37,unemployed,Rejected
23999,I need financial help to cover maternity and d...,180440,769,15259,15.06,employed,Approved

In [22]:
# Check for missing values
print("Missing values per column:")
print(df.isnull().sum())

Missing values per column:
Text                 0
Income               0
Credit_Score         0
Loan_Amount          0
DTI_Ratio            0
Employment_Status    0
Approval             0
dtype: int64

In [61]:
# Drop the 'Text' column to simplify the dataset
df = df.drop(columns=["Text"])
df

,Income,Credit_Score,Loan_Amount,DTI_Ratio,Employment_Status,Approval
0,26556,581,8314,79.26,employed,Rejected
1,197392,389,111604,22.14,employed,Rejected
2,44561,523,34118,45.44,employed,Rejected
3,190363,729,118757,10.22,unemployed,Rejected
4,61853,732,19210,44.13,employed,Approved
...,...,...,...,...,...,...
23995,195242,817,16403,24.32,employed,Approved
23996,150246,729,101572,9.97,employed,Rejected
23997,64571,650,30533,57.35,employed,Rejected
23998,115825,418,89837,10.37,unemployed,Rejected
23999,180440,769,15259,15.06,employed,Approved

In [62]:
if "Employment_Status" in df.columns:
    print("yes")

yes

In [63]:
df.columns

Index(['Income', 'Credit_Score', 'Loan_Amount', 'DTI_Ratio',
       'Employment_Status', 'Approval'],
      dtype='object')

In [64]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Create encoder
encoder = OneHotEncoder(sparse_output=False)  # use sparse_output=False to get array directly

# Fit and transform
encoded = encoder.fit_transform(df[["Employment_Status"]])

# Create DataFrame
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(["Employment_Status"]))
encoded_df

       Employment_Status_employed  Employment_Status_unemployed
0                             1.0                           0.0
1                             1.0                           0.0
2                             1.0                           0.0
3                             0.0                           1.0
4                             1.0                           0.0
...                           ...                           ...
23995                         1.0                           0.0
23996                         1.0                           0.0
23997                         1.0                           0.0
23998                         0.0                           1.0
23999                         1.0                           0.0

[24000 rows x 2 columns]

In [65]:
df = pd.concat([df, encoded_df], axis=1)
df

,Income,Credit_Score,Loan_Amount,DTI_Ratio,Employment_Status,Approval,Employment_Status_employed,Employment_Status_unemployed
0,26556,581,8314,79.26,employed,Rejected,1.0,0.0
1,197392,389,111604,22.14,employed,Rejected,1.0,0.0
2,44561,523,34118,45.44,employed,Rejected,1.0,0.0
3,190363,729,118757,10.22,unemployed,Rejected,0.0,1.0
4,61853,732,19210,44.13,employed,Approved,1.0,0.0
...,...,...,...,...,...,...,...,...
23995,195242,817,16403,24.32,employed,Approved,1.0,0.0
23996,150246,729,101572,9.97,employed,Rejected,1.0,0.0
23997,64571,650,30533,57.35,employed,Rejected,1.0,0.0
23998,115825,418,89837,10.37,unemployed,Rejected,0.0,1.0
23999,180440,769,15259,15.06,employed,Approved,1.0,0.0

In [66]:
df = df.drop(columns=["Employment_Status"])
df

,Income,Credit_Score,Loan_Amount,DTI_Ratio,Approval,Employment_Status_employed,Employment_Status_unemployed
0,26556,581,8314,79.26,Rejected,1.0,0.0
1,197392,389,111604,22.14,Rejected,1.0,0.0
2,44561,523,34118,45.44,Rejected,1.0,0.0
3,190363,729,118757,10.22,Rejected,0.0,1.0
4,61853,732,19210,44.13,Approved,1.0,0.0
...,...,...,...,...,...,...,...
23995,195242,817,16403,24.32,Approved,1.0,0.0
23996,150246,729,101572,9.97,Rejected,1.0,0.0
23997,64571,650,30533,57.35,Rejected,1.0,0.0
23998,115825,418,89837,10.37,Rejected,0.0,1.0
23999,180440,769,15259,15.06,Approved,1.0,0.0

In [67]:
df = df.drop(columns=["Employment_Status_unemployed"])
df

,Income,Credit_Score,Loan_Amount,DTI_Ratio,Approval,Employment_Status_employed
0,26556,581,8314,79.26,Rejected,1.0
1,197392,389,111604,22.14,Rejected,1.0
2,44561,523,34118,45.44,Rejected,1.0
3,190363,729,118757,10.22,Rejected,0.0
4,61853,732,19210,44.13,Approved,1.0
...,...,...,...,...,...,...
23995,195242,817,16403,24.32,Approved,1.0
23996,150246,729,101572,9.97,Rejected,1.0
23997,64571,650,30533,57.35,Rejected,1.0
23998,115825,418,89837,10.37,Rejected,0.0
23999,180440,769,15259,15.06,Approved,1.0

In [68]:
df = df.rename(columns={
    "Employment_Status_employed": "Employed"
})
df

       Income  Credit_Score  Loan_Amount  DTI_Ratio  Approval  Employed
0       26556           581         8314      79.26  Rejected       1.0
1      197392           389       111604      22.14  Rejected       1.0
2       44561           523        34118      45.44  Rejected       1.0
3      190363           729       118757      10.22  Rejected       0.0
4       61853           732        19210      44.13  Approved       1.0
...       ...           ...          ...        ...       ...       ...
23995  195242           817        16403      24.32  Approved       1.0
23996  150246           729       101572       9.97  Rejected       1.0
23997   64571           650        30533      57.35  Rejected       1.0
23998  115825           418        89837      10.37  Rejected       0.0
23999  180440           769        15259      15.06  Approved       1.0

[24000 rows x 6 columns]

In [69]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["Approval"] = le.fit_transform(df["Approval"])
df

       Income  Credit_Score  Loan_Amount  DTI_Ratio  Approval  Employed
0       26556           581         8314      79.26         1       1.0
1      197392           389       111604      22.14         1       1.0
2       44561           523        34118      45.44         1       1.0
3      190363           729       118757      10.22         1       0.0
4       61853           732        19210      44.13         0       1.0
...       ...           ...          ...        ...       ...       ...
23995  195242           817        16403      24.32         0       1.0
23996  150246           729       101572       9.97         1       1.0
23997   64571           650        30533      57.35         1       1.0
23998  115825           418        89837      10.37         1       0.0
23999  180440           769        15259      15.06         0       1.0

[24000 rows x 6 columns]

In [70]:
sample_point = [71853, 800, 17000, 50, 1]

In [71]:
from scipy.spatial.distance import euclidean

# Feature columns
features = ["Income", "Credit_Score", "Loan_Amount", "DTI_Ratio", "Employed"]

# Sample point
sample_point = [71853, 800, 17000, 50, 1]

# Calculate distances to all rows
distances = df[features].apply(lambda row: euclidean(sample_point, row), axis=1)

# Add distances to the DataFrame
df["Distance"] = distances

# View the top 5 closest rows
closest_rows = df.sort_values("Distance").head(5)
closest_rows

,Income,Credit_Score,Loan_Amount,DTI_Ratio,Approval,Employed,Distance
21150,72169,508,16928,60.93,1,1.0,436.375372
14174,72006,301,17082,11.70,1,0.0,529.718689
12321,71690,506,16541,22.67,1,0.0,569.591019
16477,72001,376,17356,27.32,1,0.0,573.525398
8096,71327,622,17664,46.03,0,1.0,865.604853

In [72]:
df=df.drop("Distance",axis=1)
df

       Income  Credit_Score  Loan_Amount  DTI_Ratio  Approval  Employed
0       26556           581         8314      79.26         1       1.0
1      197392           389       111604      22.14         1       1.0
2       44561           523        34118      45.44         1       1.0
3      190363           729       118757      10.22         1       0.0
4       61853           732        19210      44.13         0       1.0
...       ...           ...          ...        ...       ...       ...
23995  195242           817        16403      24.32         0       1.0
23996  150246           729       101572       9.97         1       1.0
23997   64571           650        30533      57.35         1       1.0
23998  115825           418        89837      10.37         1       0.0
23999  180440           769        15259      15.06         0       1.0

[24000 rows x 6 columns]

In [73]:
# the sample_point class is 1

#### KNN

In [74]:
from sklearn.model_selection import train_test_split
# Define features and label
X = df.drop(columns=["Approval"])
y = df["Approval"]

#Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [75]:
#Train KNN Model
from sklearn.neighbors import KNeighborsClassifier

# Create and train the model
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [76]:
#Evaluate the Model
from sklearn.metrics import accuracy_score, classification_report

# Predict on test set
y_pred = knn.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.818125
              precision    recall  f1-score   support

           0       0.31      0.12      0.18       753
           1       0.85      0.95      0.90      4047

    accuracy                           0.82      4800
   macro avg       0.58      0.54      0.54      4800
weighted avg       0.77      0.82      0.78      4800

In [77]:
# Sample point: Income=71853, Credit_Score=800, Loan_Amount=17000, DTI_Ratio=50, Employed=1
sample = [[71853, 800, 17000, 50, 1]]
prediction = knn.predict(sample)
print("Prediction for sample:", "Approved" if prediction[0] == 1 else "Rejected")

Prediction for sample: Approved

G:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [78]:
X_train.columns

Index(['Income', 'Credit_Score', 'Loan_Amount', 'DTI_Ratio', 'Employed'], dtype='object')

In [79]:
df

       Income  Credit_Score  Loan_Amount  DTI_Ratio  Approval  Employed
0       26556           581         8314      79.26         1       1.0
1      197392           389       111604      22.14         1       1.0
2       44561           523        34118      45.44         1       1.0
3      190363           729       118757      10.22         1       0.0
4       61853           732        19210      44.13         0       1.0
...       ...           ...          ...        ...       ...       ...
23995  195242           817        16403      24.32         0       1.0
23996  150246           729       101572       9.97         1       1.0
23997   64571           650        30533      57.35         1       1.0
23998  115825           418        89837      10.37         1       0.0
23999  180440           769        15259      15.06         0       1.0

[24000 rows x 6 columns]

In [80]:
#overfitting
# Accuracy on training set
train_accuracy = knn.score(X_train, y_train)

# Accuracy on test set
test_accuracy = knn.score(X_test, y_test)

print(f"Training Accuracy: {train_accuracy:.4f}")
print(f"Test Accuracy: {test_accuracy:.4f}")

Training Accuracy: 0.8526
Test Accuracy: 0.8181